# Port of the gateway
server:
  port: 9000

# Gateway configuration
spring:
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: lb://user-microservice
          predicates:
          - Path=/api/user/**
          filters:
          - RewritePath=/api/user(?<segment>), /user$\{segment}

        - id: package_route
          uri: lb://package-microservice
          predicates:
          - Path=/api/package/**
          filters:
          - RewritePath=/api/package(?<segment>), /package$\{segment}

        - id: class_route
          uri: lb://class-microservice
          predicates:
          - Path=/api/class/**
          filters:
          - RewritePath=/api/class(?<segment>), /class$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: health,refresh

eureka:
  client:
    registerWithEureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
